### PR TITLE
Pl reflpron

### PR DESCRIPTION
**Pull request by ppski**

### CODE REVIEW

**Comment by inariksit** [comment]
Aarne just added a construction to Extend for `ReflPossPron : Quant`, so you can put the reflPron in there! 
Here's the change: [6fee9d7](https://github.com/GrammaticalFramework/gf-rgl/commit/6fee9d712aa99fa1c1154417326b518ab2c02a31)

**Comment by inariksit** [comment]
Btw, no need to worry about the "failing build" messages, it's just the Windows build that's failing all the time. So you can just make a new commit, no need to fix anything else or make a new PR.

**Comment by inariksit** [comment]
Sorry, with "there" I mean ExtendPol, not StructuralPol. You can look for example in e.g. ExtendCze. https://github.com/GrammaticalFramework/gf-rgl/blob/6fee9d712aa99fa1c1154417326b518ab2c02a31/src/czech/ExtendCze.gf

**Comment by ppski** [comment]
@inariksit Would it be OK to keep it as is? ExtendPol doesn't exist. I assumed that the CZ pronouns were put in Extend because they are done in a "different" way than the other CZ possessive pronouns in StructuralCze.gf. The Polish ReflPossPron is created in the same way as the other possessive pronouns so I kept them in StructuralPol.gf

Does that make sense? Or should I create ExtendPol? I'm guessing that ExtraPol might be to Pol what ExtendCze is to Cze.

**Comment by ppski** [comment]
Ah...but `ReflPossPron` is a `Quant`, not a `Pron`! I will redo the addition.

**Comment by aarneranta** [comment]
The main reason of putting ReflPossPron into ExtenCze is that it is not available (or even relevant) for all languages. I guess the same would make sense for Pol as well, but can also be postponed. I can take a look at initializing ExtendPol later. My experience with Cze and Slo was that it can be a bit tricky to get this module started.



________________________________

**Comment by ppski** [comment]
@inariksit @aarneranta Would it be possible to merge this branch as it is, with the PL pronoun in PronounMorphoPol.gf?

**Comment by inariksit** [comment]
Sure, we can do the rest later! Merging now.

**Comment by ppski** [comment]
Nice, thanks for all the attention with this!

**Pull request merged**
