### PR TITLE
(Romance,Por) allow Romance Languages to choose different verb forms for the same tense/anteriority

### PR DESCRIPTION
**Pull request by odanoburu**
for Portuguese it's best to
- pick imperfect tense when tense/anteriority is present anterior
- pick perfect tense when tense/anteriority is past simultaneous

this increases compilation times for Portuguese in 10 seconds though.

### CODE REVIEW

**Comment by inariksit** [comment]
> pick perfect tense when tense/anteriority is past simultaneous

By perfect, do you mean the form that is in French called passe simple, in Spanish pretérito and so on? This seems like a reasonable change, especially given that the RGL itself is nowadays often used as a base for applications, so it's nice to get good translation equivalents out of the box. 

I suggest you document this change in the README for Portuguese, so application grammarians know not to expect *eu hei dormido* for present anterior, like in other Romance functor languages.

**Comment by odanoburu** [comment]
> By perfect, do you mean the form that is in French called passe simple, in Spanish pretérito and so on? 

yes! but in Portuguese and Spanish we don't use the auxiliary like in French, and the current Romance functor only allows the use of these through the Extra module.. btw, should I make the change for spanish too?


> This seems like a reasonable change, especially given that the RGL itself is nowadays often used as a base for applications, so it's nice to get good translation equivalents out of the box.

yes, I feel like using the Extra module would be unnecessary overhead here, because it's for something rather basic!

> I suggest you document this change in the README for Portuguese, so application grammarians know not to expect eu hei dormido for present anterior, like in other Romance functor languages.

will do!

**Comment by inariksit** [comment]
> yes! but in Portuguese and Spanish we don't use the auxiliary like in French, and the current Romance functor only allows the use of these through the Extra module.. btw, should I make the change for spanish too?

I think someone Spanish-speaking would need to confirm this. I have the feeling that the form *he dormido* is not uncommon, but I might be mistaken, or there could be differences between European and Latin American usages and we're both correct on the variant that is spoken in our respective continents. :-P For Portuguese I thought no problem to get rid of *hei dormido*, because I trust your language sense for that change, and Portuguese is a new language in the RGL, so it won't break any application.

The question about préterito vs. imperfecto for `TPast ASimul` I don't really have a good opinion on; both are common in Spanish and Portuguese, and are used for different things. It's a similar kind of issue than e.g. politeness forms for Japanese; the RGL abstract syntax just doesn't have the distinctions, so you choose one and leave others for Extra. The only reason to prefer one over other is that the Romance functor languages have had imperfecto for `TPast ASimul` already for years.

Actually, this seems like the kind of issue that needs to be discussed on the mailing list first! The tradeoffs are idiomatic translations by using RGL vs. uniformity between Romance functor languages.

**Comment by inariksit** [comment]
@odanoburu actually now that I think of it, would it be a solution to leave `TPast ASimul` in pretérito imperfeito (*dormia*), but just change `TPres AAnter` into pretérito perfeito (*dormi*).
Then all Romance functor languages would have `TPast ASimul`=>*dormia*, but we could still avoid the rare *hei dormido* in Portuguese. Does that sound reasonable?

(To add to the confusion, in Spanish, *he dormido* is called "pretérito perfecto" https://es.wiktionary.org/wiki/dormir#Conjugaci%C3%B3n , that's why I asked in the first comment which form you meant! but okay I will always add an inflected form like *dormi* to make it clear which form I mean :-D)

**Pull request merged**
