### PR TITLE
Unit testing for RGL languages, written in Python 2+3

### PR DESCRIPTION
**Pull request by heatherleaf**
Here's a Python 2+3 script for unit testing of RGL languages, as discussed in #118 

It needs `gf` available from the command line, and Python of course. No other dependencies (I hope)

I have only tested it on Mac (10.14 Mojave), using Python 2.7 and 3.7

### CODE REVIEW

**Comment by johnjcamilleri** [comment]
This is a good initiative, but we should think about pushing this to be the standard way of testing the RGL. At the very least I think it should be moved from `src` into `tests`, replacing whatever's already there if we consider that to be deprecated.

Then it should have a standalone README, and a few ready-made unit tests for people to try out but which can become the basis for a standard test suite, run by Travis on every commit etc.

**Comment by krangelov** [comment]
Also since there is a build script for the RGL in Haskell, it would be
better to use Haskell here as well. Otherwise we just make the zoo of
languages bigger.

На ср, 10.07.2019 г., 10:05 John J. Camilleri <notifications@github.com>
написа:

**Comment by johnjcamilleri** [comment]
> Also since there is a build script for the RGL in Haskell, it would be
better to use Haskell here as well. Otherwise we just make the zoo of
languages bigger.

Well, the whole reason we have the `.sh` and `.bat` build scripts is to allow people to build the RGL without needing to install Haskell, which may be a barrier to entry for some. I think having a non-Haskell testing script makes sense, so that we can attract RG devs without requiring them to install Haskell.

It's true that this PR adds a new language (Python) to the mix, although one might argue that Python is ubiquitous enough that we can just assume most people already have it. I'm guessing no one in interested in re-implementing this test script in both Shell and Batch 😣

**Comment by krangelov** [comment]
Script in shell/batch would fit best but it may not be possible. Otherwise,
I actually still use the Haskell script.

Using Python is not big deal but it feels a bit odd to me when everything
else is Haskell. There could be also something like:

runghc Setup.hs test

for testing.



На ср, 10.07.2019 г., 12:35 John J. Camilleri <notifications@github.com>
написа:

**Comment by heatherleaf** [comment]
> Well, the whole reason we have the `.sh` and `.bat` build scripts is to allow people to build the RGL without needing to install Haskell, which may be a barrier to entry for some. I think having a non-Haskell testing script makes sense, so that we can attract RG devs without requiring them to install Haskell.
>
> It's true that this PR adds a new language (Python) to the mix, although one might argue that Python is ubiquitous enough that we can just assume most people already have it.

That's exactly the reasons why I chose Python.

I wouldn't say no to a similar Haskell test script -- the test file format is simple enough, so the Haskell code shouldn't be too complicated. But I won't write it...

**Comment by heatherleaf** [comment]
> This is a good initiative, but we should think about pushing this to be the standard way of testing the RGL. At the very least I think it should be moved from `src` into `tests`, replacing whatever's already there (if we consider that to be deprecated).

I created the directory `unittest` -- someone else (@aarneranta ?) can deprecate the `tests` directory. 

> Then it should have a standalone README, and a few ready-made unit tests for people to try out and which can also form the basis for a standard RGL test suite, run by Travis on every commit etc.

There is an example test file now, but no README -- I don't know what to put in that except what's already written in the Python file

**Comment by inariksit** [comment]
Great initiative! I have no strong opinions about Python; it seems to me pretty standard.

I have a feature request. Some languages are terribly slow to parse (e.g. uses 18GB memory trying to parse a sentence and still doesn't finish), but linearisation works fine. It would be nice to be able to specify a tree and just verify that linearisation produces the expected result, without being forced to parse. Especially if we want Travis to run the tests at every commit. Now it's just compiling the grammars with `--no-pmcfg`, which is manageable even for the worst languages.

Another improvement for slow languages would be to open the GF grammar with flags `-retain` and `-no-pmcfg`, and linearising the tree with `cc` instead of `l`.

**Comment by inariksit** [comment]
@heatherleaf Here's my implementation of the features I requested: https://github.com/inariksit/gf-rgl/blob/unittest-python-script/unittest/unittest.py If it's bad Python I'm sorry, I wrote it when I was stuck on a local train without internet :-D It runs in half a second with the option `-only-cc` even for a language with a massive PGF. I will be using that for myself in any case.

**Comment by heatherleaf** [comment]
> @heatherleaf I added my implementation of the features I requested, as a flag `-only-cc`. Running the file without the flag works like it used to. With `-only-cc` it runs in half a second even for a language that doesn't parse with the original script.

@inariksit Thanks for the idea! I'm reimplementing the script now to make it simpler, but have one question:

Why do you use `-gfo-dir=/tmp`? Is there a problem with letting the gfo directory be the default?

**Comment by inariksit** [comment]
No, there's no problem, it works equally fine without `-gfo-dir=/tmp`!

**Comment by heatherleaf** [comment]
I've updated the script and it feels quite mature now.

@inariksit Note that the flag `-only-cc` is renamed to `--no-pmcfg`

@johnjcamilleri @aarneranta @krangelov @inariksit What do you think? Is the PR mature enough to merge in the main branch?

**Comment by johnjcamilleri** [comment]
> I've updated the script and it feels quite mature now.

Hmm have you pushed? I cannot see any recent updates by you.

**Comment by heatherleaf** [comment]
> Hmm have you pushed? I cannot see any recent updates by you.

Yes, it just took a little while for github to recognise the new commits... now they are in the PR too

**Comment by heatherleaf** [comment]
@krangelov @aarneranta 
What do you think? Is it mature enough to merge into the main branch?

**Comment by heatherleaf** [comment]
Since noone has objected, I merge this PR

**Pull request merged**
