### PR TITLE
Arabic

### PR DESCRIPTION
**Pull request by inariksit**

### CODE REVIEW

**Comment by Thomas-H** [comment]
This causes build failures:

```src/arabic/ResAra.gf:
   src/arabic/ResAra.gf:1287-1297:
     Happened in operation mkPron
      no applicable case for Bare
OCCURRED IN
trying patterns Nom, Acc, Gen, Dat
gf exited with exit code: 1
make: *** [build] Error 1
```

The Travis build script seems buggy, it reports success in spite of this failure.

**Comment by inariksit** [comment]
Sorry about that. My latest pull request (currently in check) should fix that. Could @odanoburu or someone else who has developed it have a look at the travis script?

**Comment by odanoburu** [comment]
I'm on it! I'm checking on my fork though, because I can't see the logs from here

**Comment by odanoburu** [comment]
[fixed](https://travis-ci.org/odanoburu/gf-rgl/jobs/457046846), it was totally my fault!

I was doing

```
runghc Make.hs build prelude all --verbose ; rm -rf dist
```
and of course `rm -rf dist` would always exit successfully.

**Pull request merged**
