### PR TITLE
Request for Merge

### PR DESCRIPTION
**Pull request by bamutra**
Hello, kindly authorise a merge between my rgl and the main rgl because I want to make a fresh pull request for the rgl as a whole.

### CODE REVIEW

**Comment by inariksit** [comment]
Can you resolve the conflict in languages.csv, and put Cgg in the right place in alphabetic order?

**Comment by bamutra** [comment]
Alright

I just did that !!!

On 26 Oct 2020, at 09:42, Inari Listenmaa <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you resolve the conflict in languages.csv, and put Cgg in the right place in alphabetic order?

**Comment by inariksit** [comment]
Thanks for the changes! However, two things:

1. There's still conflict in languages.csv. What I can see by just looking is that the header line `Code,Name,Directory,Functor,Unlexer,Present,All,Try,Symbolic,Compatibility,Synopsis` is missing, and some languages too, like Korean from line 26. Double check that you have merged in the latest version, at [gf-rgl/languages.csv](github.com/GrammaticalFramework/gf-rgl/blob/master/languages.csv)

2. The comments in Coordination.gf could be more informative. I appreciate that you have added them--that module is pretty cryptic. Here are my suggestions for comments, to replace the ones you wrote.

* I'd start by explaining what the ListX is for, and a short example.
```haskell
  -- Type of [X] for any X whose lincat is {s : Str}.
  -- example : ListX = {s1 = "a , b" ; s2 = "c"}
  ListX = {s1,s2 : Str} ;
```

* The second two are just helper functions, the real interesting part is in `twoSS` and `conjSS`. So I skip talking about them in particular, and just label them as helpers.

```haskell
  -- Helper funs for twoSS and conjSS
  twoStr : (x,y : Str) -> ListX = \x,y ->
    {s1 = x ; s2 = y} ;
  consStr : Str -> ListX -> Str -> ListX = \comma,xs,x ->
    {s1 = xs.s1 ++ comma ++ xs.s2 ; s2 = x } ;
```

* And here are the interesting things. I've put an example in all of them. Also I want to highlight that the separator doesn't necessarily need to be comma.

```haskell
  -- Create a ListX from two Xs. Example:
  --     x = {s = "here"} ;
  --     y = {s = "there"} ;
  -- twoSS x y ==> {s1 = "here" ; s2 = "there"}
  twoSS : (_,_ : SS) -> ListX = \x,y ->
    twoStr x.s y.s ;

  -- Add new X to a ListX, along with a separator. Example:
  --     comma = ","
  --     xs = {s1 = "here" ; s2 = "there"}
  --     x = {s = "everywhere"}
  -- consSS comma xs x ==> {s1 = "here , there" ; s2 = "everywhere"}
  consSS : Str -> ListX -> SS -> ListX = \comma,xs,x ->
    consStr comma xs x.s ;

  -- Apply conjunction to a ListX to form an X. Example:
  --   or = {s1 = "" ; s2 = "and"}
  --   xs = {s1 = "here , there" ; s2 = "everywhere"}
  -- conjunctX or xs = {s = "here, there and everywhere"}
  conjunctX : Conjunction -> ListX -> Str = \or,xs ->
    xs.s1 ++ or.s ++ xs.s2 ;
```

* And finally some info about tables. I don't know what you mean by type families--to me, and probably for many GF users, that name suggests Haskell's type families, which isn't really what's going on here. This is more like a normal type alias in Haskell, like `type ListTable P = … P`. So I'd remove the comment about type families, and write this instead.

```haskell

  -- Type for a table with the given parameter P on the LHS.
  -- For example, if the lincat for X is {s : Number => Str},
  -- then the lincat for [X] should be ListTable Number,
  -- which expands to {s1, s2 : Number => Str}.
  ListTable : PType -> Type = \P -> {s1,s2 : P => Str} ;
```

If I misunderstood your comments, or you don't agree with some of my versions, let me know!

**Comment by inariksit** [comment]
I did the changes manually. Before you continue working in your local branch, remember to merge my changes to languages.csv, Coordination.gf and ParadigmsCgg.gf. (There was a duplicated `-path` in ParadigmsCgg, so I fixed that meanwhile I was doing the other things.)

**Pull request merged**
