### PR TITLE
pull

### PR DESCRIPTION
**Pull request by kitukb**

### CODE REVIEW

**Comment by inariksit** [comment]
Hi @kitukb ,

4 months ago, I renamed your grammar from kiswahili to swahili, and put the old Swahili grammar in src/swahili/old. See the related [issue](https://github.com/GrammaticalFramework/gf-rgl/issues/106) and [pull request](https://github.com/GrammaticalFramework/gf-rgl/pull/341). Could you please merge your updates to the new naming scheme?

**Comment by kitukb** [comment]
@inariksit i saw it and i have adjusted the one i have

**Comment by kitukb** [comment]
@inariksit have see it and adjusted where necessary, should be sending an update

**Comment by inariksit** [comment]
Okay, great!

**Pull request closed without merging**
