### PR TITLE
use docker for ci

### PR DESCRIPTION
**Pull request by odanoburu**
using dockerfile in https://github.com/odanoburu/docker-gf/blob/master/haskell-gf/Dockerfile

basically, this takes the standard haskell docker image, installs gf using the .deb file, and then runs the `Make.sh` and `Make.hs` scripts.

1. there seems to exist a missing file in the mongolian language, which is why I excluded it.
2. I've tested it again, and `Make.hs` will fail the build when there are errors, but `Make.sh` won't; apparently we have to change it to exit with non-zero codes when its calls to gf go awry.
3. two days ago I've helped someone build GF on their computer, and the haskell script failed, while the shell one worked fine. the same happens in docker, unless I build with shell script first. I suspect it is a problem in the script: running `GF_LIB_PATH=/home/rgl runghc Make.hs build --langs=-Mon --dest=rgl` with a clean gf-rgl directory (removing the dist/ directory) throws an error, while using the usual GF_LIB_PATH works fine.

I don't think this should be merged until we figure out what seems to be a problem in Make.hs. can you reproduce the error in 3.?

### CODE REVIEW

**Comment by odanoburu** [comment]
hello @johnjcamilleri 

1. no, Make.hs still seems to be hanging at
```
File Prelude.gf does not exist.
searched in: src/afrikaans/
             /home/src/afrikaans
             /home/dist
             /home/src/abstract
             /home/src/common
             /home/dist/alltenses
```
do you know why is this? I can reproduce this in my machine too, provided I remove the `dist` directory and GF_LIB_PATH.

2. indeed! it now fails with the same error as in 1. on another note, should its shebang be `/bin/bash`, though? when running with `--verbose` (good call!) it shows a few syntax warnings that seem to be fine with bash.

3. thanks, I removed the `--dest` flag! but I still can't build because of 1...

**Comment by odanoburu** [comment]
it seems that running `runghc Make.hs build all` doesn't build prelude before building present; when I do `runghc Make.hs build prelude` and then `runghc Make.hs build all`, it seems to work (I've tested it locally). can you confirm this?

**Comment by johnjcamilleri** [comment]
> it seems that running runghc Make.hs build all doesn't build prelude before building present; when I do runghc Make.hs build prelude and then runghc Make.hs build all, it seems to work (I've tested it locally). can you confirm this?

That is correct, and this is by design. One mistake in the README is that it says the default is `all`, whereas actually the default is `prelude all`. So the solution is simply to use one of the following:

```
$ runghc Make build prelude all
$ runghc Make build
```

**Comment by johnjcamilleri** [comment]
> should its shebang be /bin/bash, though?

You're probably right. `[[` is Bash-specific, isn't it? I updated just now. The build is still failing with:

```
Make.sh: line 66: ./bin/gf: No such file or directory
```

**Comment by johnjcamilleri** [comment]
I think it should be `./bin/bin/gf`

**Comment by johnjcamilleri** [comment]
(Please ignore my two previous comments, I was looking at the wrong build on Travis)

> should its shebang be `/bin/bash`, though?

You're probably right. `[[` is Bash-specific, isn't it? I updated just now. But I guess the `travis.yml` also needs updating, as you are calling the script with `sh` there.

I'm not the best shell scripter so there may be other little bugs in there...

**Comment by odanoburu** [comment]
@johnjcamilleri does `all` build `present` and `alltenses` only? if so, should we build the other things too?

> But I guess the travis.yml also needs updating, as you are calling the script with sh there.

yep, thanks! I changed sh to bash in the previous commit, but I missed the call to Make.sh! 

the build now works for Make.hs, but is still failing for Make.sh, apparently because it doesn't build the prelude before present either!

**Comment by odanoburu** [comment]
> I'm not the best shell scripter so there may be other little bugs in there...

btw, https://www.shellcheck.net throws very little warnings on your script, so I guess you are probably much better than average -- is there anyone who is actually great at shell scripting? my scripts are always full of errors before checking!

**Comment by johnjcamilleri** [comment]
> the build now works for Make.hs, but is still failing for Make.sh, apparently because it doesn't build the prelude before present either!

Huh? That can't be right; it says so right [here](https://travis-ci.org/GrammaticalFramework/gf-rgl/builds/414559812#L584).
Something else is afoot here.

**Comment by johnjcamilleri** [comment]
> does `all` build `present` and `alltenses` only? if so, should we build the other things too?

They are referring to different things. `all` refers to modules (Lang, Try, Symbolic etc.) while `present` refers to building a minimal version of a language with only the present tense (only a few languages are marked for this).
So to answer your question, `prelude all` is sufficient and there is nothing else which needs to be build in addition.

**Comment by odanoburu** [comment]
> Huh? That can't be right; it says so right here.
Something else is afoot here.

you're right! testing locally, it seems that the `--dest` flag is not being honored, or maybe its contents are only transferred there after the build is complete. as `GF_LIB_PATH` is not set there, the build doesn't look there for `Prelude.gf`:
```
File Prelude.gf does not exist.
searched in: src/afrikaans/
             /home/src/afrikaans
             /home/rgl
             /home/src/abstract
             /home/src/common
```

so I'll just use the dist directory as the `GF_LIB_PATH`, instead of creating a new one just for this.

> So to answer your question, prelude all is sufficient and there is nothing else which needs to be build in addition.

:+1:

**Comment by johnjcamilleri** [comment]
Latest commit 989c6f58 should fix this.

**Comment by odanoburu** [comment]
it does!

**Pull request merged**
